# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: News
    url: news
    weight: 20
  #- name: Speakers
    #url: people
    #weight: 30
  #- name: Events
    #url: event
    #weight: 40
  - name: Q&A
    url: q&a
    weight: 50
  #- name: Contact
    #url: contact
    #weight: 60
  #- name: Github
    #url: https://github.com/Shef-AIRE
    #weight: 70
